name: Félix

on:
  push:
    branches:
      - main
      
jobs:
  generate-file-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install --upgrade pip

      - name: Generate music list
        run: python generate_music_list.py
        
      - name: Stash changes
        run: git stash --include-untracked
        
      - name: Pull with rebase
        run: git pull --rebase
        
      - name: Apply stashed changes
        run: git stash pop


      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add music.json
          git commit -m "Update" -m "music.json"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
